// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var Css = require("@emotion/css");

function DisplayPanel(Props) {
  var container = Css.css({
        display: "flex",
        justifyContent: "flex-end",
        alignItems: "flex-end",
        width: "100%",
        height: "35%",
        backgroundColor: "salmon"
      });
  var display = Css.css({
        width: "auto",
        height: "auto",
        overflowWrap: "break-word",
        textAlign: "right",
        fontSize: "35px",
        margin: "20px"
      });
  var match = Utils.useCalculator(undefined);
  return React.createElement("div", {
              className: container
            }, React.createElement("h1", {
                  className: display
                }, match[0]));
}

var make = DisplayPanel;

exports.make = make;
/* Utils Not a pure module */
