// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Axios = require("axios");
var React = require("react");
var $$Promise = require("reason-promise/src/js/promise.bs.js");

function useDataConsumer(param) {
  var match = React.useState(function () {
        return [];
      });
  var setData = match[1];
  var getUsers = function (param) {
    $$Promise.tapError($$Promise.tapOk($$Promise.Js.toResult(Axios.get("https://run-sql-xliijuge3q-dt.a.run.app/limit?limit=10", undefined)), (function (res) {
                return Curry._1(setData, res.data.users);
              })), (function (err) {
            var e = err.response;
            if (e !== undefined && e.status === 404) {
              console.log("Not found");
            } else {
              console.log("an error occured", e);
            }
            
          }));
    
  };
  React.useEffect((function () {
          getUsers(undefined);
          
        }), []);
  return match[0];
}

exports.useDataConsumer = useDataConsumer;
/* axios Not a pure module */
